version: '3.9'
services:
  java_app:
    container_name: java_app
    image: pee-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgresp
      - DATABASE_USERNAME=postgresp
      - DATABASE_PASSWORD=postgresdockerp
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:15.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgresp
      - POSTGRES_PASSWORD=postgresdockerp
      - POSTGRES_DB=postgresp
    volumes:
      - ./pg_data:/var/lib/postgresql/data